### ISSUE TITLE
add each other to the repos

### ISSUE THREAD

**Issue by calvinmetcalf** [crypto-browserify/ownership#1]
@dcousens @jprichardson @dominictarr I added you all as npm authers on all of the packages I have re crypto, you can do it for your packages by cloning this repo, editing the crypto-packages.json to include your packages, then run `npm install -g` and `crypto-ownership-all`

**Comment by jprichardson** [comment]
Ok... will do. Btw... I'm `jp` on npm :) https://www.npmjs.com/~jp I probably should have chosen `jprichardson`. Not sure if it's too late to change?

**Comment by jprichardson** [comment]
I updated https://github.com/crypto-browserify/ownership/blob/master/crypto-users.json for the time being with (`jp`) and sent npm inc an email about merging the two profiles. Added all of you as owner.

**Comment by calvinmetcalf** [comment]
I'm updating the client to have an ownership remove function

**Comment by calvinmetcalf** [comment]
ok cleaned up all the jprichardson stuff, no big deal, I do the same thing with a different npm name
